<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");

metatagrazdel(
    'forum', // link
    'Форум Российского юридического портала', // title
    '',//SetTitle
    '', // tags
    'форум, российский юридический портал, обманутые дольщики, обманутые вкладчики, автомобильный форум, форум призывников, семейный форум', // keywords
    'Юридический форум jur24pro. Создавайте свои темы и на них ответят аккредитованные юристы, адвокаты и помогут Вам.', // description
    'Форум Российского юридического портала' // h1
);
?>

<div class="wrap">

<?$APPLICATION->IncludeComponent(
	"bitrix:forum", 
	"forum", 
	array(
		"AJAX_POST" => "N",
		"ATTACH_MODE" => array(
			0 => "THUMB",
			1 => "NAME",
		),
		"ATTACH_SIZE" => "500",
		"CACHE_TIME" => "31536000",
		"CACHE_TIME_FOR_FORUM_STAT" => "3600",
		"CACHE_TIME_USER_STAT" => "60",
		"CACHE_TYPE" => "A",
		"CHECK_CORRECT_TEMPLATES" => "N",
		"COMPONENT_TEMPLATE" => "forum",
		"DATE_FORMAT" => "d.m.Y",
		"DATE_TIME_FORMAT" => "d.m.Y H:i:s",
		"EDITOR_CODE_DEFAULT" => "N",
		"FID" => array(
			0 => "1",
			1 => "124",
			2 => "125",
			3 => "126",
			4 => "127",
			5 => "128",
			6 => "129",
			7 => "130",
			8 => "131",
			9 => "132",
			10 => "133",
			11 => "134",
			12 => "135",
			13 => "136",
			14 => "137",
			15 => "138",
			16 => "139",
			17 => "140",
			18 => "141",
			19 => "142",
			20 => "143",
			21 => "144",
			22 => "145",
			23 => "146",
			24 => "147",
			25 => "148",
			26 => "149",
			27 => "150",
			28 => "151",
			29 => "152",
			30 => "153",
		),
		"FILES_COUNT" => "5",
		"FORUMS_PER_PAGE" => "100",
		"HELP_CONTENT" => "",
		"IMAGE_SIZE" => "500",
		"MESSAGES_PER_PAGE" => "100",
		"NAME_TEMPLATE" => "",
		"NO_WORD_LOGIC" => "N",
		"PAGE_NAVIGATION_TEMPLATE" => "forum",
		"PAGE_NAVIGATION_WINDOW" => "5",
		"PATH_TO_AUTH_FORM" => "",
		"PATH_TO_ICON" => "/bitrix/images/forum/icon/",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"RESTART" => "N",
		"RSS_CACHE" => "1800",
		"RSS_COUNT" => "30",
		"RSS_TN_DESCRIPTION" => "",
		"RSS_TN_TITLE" => "",
		"RSS_TYPE_RANGE" => array(
			0 => "RSS1,RSS2,ATOM",
		),
		"RULES_CONTENT" => "",
		"SEF_FOLDER" => "/forum/",
		"SEF_MODE" => "Y",
		"SEND_ICQ" => "A",
		"SEND_MAIL" => "E",
		"SEO_USER" => "N",
		"SEO_USE_AN_EXTERNAL_SERVICE" => "N",
		"SET_DESCRIPTION" => "N",
		"SET_NAVIGATION" => "N",
		"SET_PAGE_PROPERTY" => "N",
		"SET_TITLE" => "Y",
		"SHOW_AUTHOR_COLUMN" => "N",
		"SHOW_AUTH_FORM" => "Y",
		"SHOW_FIRST_POST" => "N",
		"SHOW_FORUMS" => "N",
		"SHOW_FORUM_ANOTHER_SITE" => "Y",
		"SHOW_FORUM_USERS" => "N",
		"SHOW_LEGEND" => "N",
		"SHOW_NAME_LINK" => "Y",
		"SHOW_NAVIGATION" => "N",
		"SHOW_RATING" => "N",
		"SHOW_STATISTIC" => "Y",
		"SHOW_STATISTIC_BLOCK" => array(
		),
		"SHOW_SUBSCRIBE_LINK" => "N",
		"SHOW_TAGS" => "Y",
		"SHOW_VOTE" => "N",
		"SMILES_COUNT" => "100",
		"THEME" => COption::GetOptionString("main","wizard_".SITE_TEMPLATE_ID."_forum_theme_id","gray",SITE_ID),
		"TIME_INTERVAL_FOR_USER_STAT" => "10",
		"TMPLT_SHOW_ADDITIONAL_MARKER" => "",
		"TOPICS_PER_PAGE" => "300",
		"USER_FIELDS" => array(
		),
		"USER_PROPERTY" => array(
		),
		"USE_LIGHT_VIEW" => "Y",
		"USE_NAME_TEMPLATE" => "N",
		"USE_RSS" => "N",
		"WORD_LENGTH" => "50",
		"WORD_WRAP_CUT" => "23",
		"SEF_URL_TEMPLATES" => array(
			"index" => "index.php",
			"list" => "forum#FID#/",
			"read" => "forum#FID#/topic#TID#/",
			"message" => "messages/forum#FID#/topic#TID#/message#MID#/",
			"help" => "help/",
			"rules" => "rules/",
			"message_appr" => "messages/approve/forum#FID#/topic#TID#/",
			"message_move" => "messages/move/forum#FID#/topic#TID#/message#MID#/",
			"rss" => "rss/#TYPE#/#MODE#/#IID#/",
			"search" => "search/",
			"subscr_list" => "subscribe/",
			"active" => "topic/new/",
			"topic_move" => "topic/move/forum#FID#/topic#TID#/",
			"topic_new" => "topic/add/forum#FID#/",
			"topic_search" => "topic/search/",
			"user_list" => "users/",
			"profile" => "user/#UID#/edit/",
			"profile_view" => "user/#UID#/",
			"user_post" => "user/#UID#/post/#mode#/",
			"message_send" => "user/#UID#/send/#TYPE#/",
			"pm_list" => "pm/folder#FID#/",
			"pm_edit" => "pm/folder#FID#/message#MID#/user#UID#/#mode#/",
			"pm_read" => "pm/folder#FID#/message#MID#/",
			"pm_search" => "pm/search/",
			"pm_folder" => "pm/folders/",
		)
	),
	false
);?>
</div>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>